# ~/.gnupg/scdaemon.conf
disable-ccid

# attempt to make pin caching work again
# https://dev.gnupg.org/T5436
disable-application piv

pcsc-shared
# sudo apt install libpcsclite-dev
#pcsc-driver /usr/lib/x86_64-linux-gnu/libpcsclite.so.1
#pcsc-driver /usr/lib/x86_64-linux-gnu/libpcsclite.so
#pcsc-driver /usr/lib/libpcsclite.so
#pcsc-driver /snap/yubioath-desktop/current/usr/lib/libpcsclite.so
#pcsc-driver libpcsclite.so.1
card-timeout 5

debug-level basic
log-file ~/.gnupg/scdaemon.log
